language: node_js

node_js:
  - "7.8"

# services:
#   - docker

# branches:
#  only:
#    - master


before_install:
  - npm install -g mocha chai

install:
  - npm install;

script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_DIR
  - echo $TRAVIS_BUILD_ID
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_BUILD_COMMIT
  - echo $TRAVIS_COMMIT_MESSAGE
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_EVENT_TYPE
  - echo $TRAVIS_JOB_ID
  - echo $TRAVIS_JOB_NUMBER
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_PULL_REQUEST_SLUG
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS
  - echo $TRAVIS_SUDO
  - echo $TRAVIS_TEST_RESULT
  - echo $TRAVIS_TAG
  - npm run test;

# after_success:
#   - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ] &&  curl --data build=true docker_tag=$TRAVIS_TAG -X POST $DOCKER_BUILD_URL'

# after_success:
#   - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#    docker build -t zpydee/build-tester:$TRAVIS_TAG .;
#    docker push zpydee/build-tester:$TRAVIS_TAG;
#    fi