language: node_js

node_js:
  - "7.8"

services:
  - docker

branches:
 only:
   - master
   - /17\.(\d+)/

env:
  global:
    DOCKER_REPO=zpydee/build-tester

before_install:
  - npm install -g mocha chai

install:
  - npm install;

script:
  - npm run test;

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == false ]; then
    export BRANCH_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "staging"; else echo $TRAVIS_BRANCH; fi`;
    export COMMIT_TAG=`echo $BRANCH_TAG-${TRAVIS_COMMIT::7}`;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t $DOCKER_REPO:$COMMIT_TAG .;
    docker tag $DOCKER_REPO:$COMMIT_TAG $DOCKER_REPO:$BRANCH_TAG;
    docker push $DOCKER_REPO;
    fi