language: node_js

node_js:
  - "7.8"

services:
  - docker

# branches:
#  only:
#    - master

env:
  global:
    DOCKER_REPO=zpydee/build-tester

before_install:
  - npm install -g mocha chai

install:
  - npm install;

script:
  - npm run test;

after_success:
  - export COMMIT_TAG=`echo ${TRAVIS_COMMIT::7}`
  - export BRANCH_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t $DOCKER_REPO:$BRANCH_TAG-$COMMIT_TAG .
  - docker tag $DOCKER_REPO:$COMMIT_TAG $DOCKER_REPO:$BRANCH_TAG
  - docker push $DOCKER_REPO


  # - if [ "$TRAVIS_BRANCH" == "master" ]; then
  #   export BRANCH_TAG = "latest"; else
  #   export BRANCH_TAG = $TRAVIS_BRANCH;
  #   fi


# after_success:
#   - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ] &&  curl --data build=true docker_tag=$TRAVIS_TAG -X POST $DOCKER_BUILD_URL'

# after_success:
#   - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#    docker build -t zpydee/build-tester:$TRAVIS_TAG .;
#    docker push zpydee/build-tester:$TRAVIS_TAG;
#    fi

after success: